@localhost = http://localhost:8000

### GET /employees
GET {{localhost}}/employees

### GET /employees/:id
GET {{localhost}}/employees/3

### GET /employees/search?name=IT
GET {{localhost}}/employees?name=john

### POST /employees
POST {{localhost}}/employees
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@Gmail.com",
    "departmentId": 120
}

### PUT /employees/:id
PUT {{localhost}}/employees/1
Content-Type: application/json

{
    "name": "John Doe",
    "age": 30,
    "department": "IT"
}

### DELETE /employees/:id
DELETE {{localhost}}/employees/1


### Projects Endpoints ###

### GET all projects
GET {{localhost}}/projects

### GET project by id
GET {{localhost}}/projects/1

### Create new project

POST {{localhost}}/projects
Content-Type: application/json

{
    "name": "Dummy project"
}
### Create many new projects
POST {{localhost}}/projects/many
Content-Type: application/json

[
    {       
        "name": "E-commerce Platform"
    },
    {     
        "name": "Mobile Banking App"
    },
    {       
        "name": "Healthcare Management System"
    },
    {      
        "name": "Inventory Management"
    },
    {      
        "name": "Social Media Analytics"
    }
]

### Update project
PATCH {{localhost}}/projects/1
Content-Type: application/json

{
    "name": "projectService"
}

### Delete project
DELETE {{localhost}}/projects/1

### find a project
GET {{localhost}}/projects/122
