@localhost = http://localhost:8000

### Departments Endpoints ###

### GET all departments
GET {{localhost}}/departments

### GET department by id
GET {{localhost}}/departments/1

### Create new department
POST {{localhost}}/departments
Content-Type: application/json

{
    "name": "Dummy Department"
}

### Create many new departments
POST {{localhost}}/departments/many
Content-Type: application/json

[
    {
        "name": "IT Department"
    },
    {
        "name": "HR Department"
    },
    {
        "name": "Finance Department"
    },
    {
        "name": "Marketing Department"
    },
    {
        "name": "Operations Department"
    }
]

### Update department
PATCH {{localhost}}/departments/1
Content-Type: application/json

{
    "name": "HR Department"
}

### Delete department
DELETE {{localhost}}/departments/1

### Search department
GET {{localhost}}/departments?name=IT
### Projects Endpoints ###

### GET all projects
GET {{localhost}}/projects

### GET project by id
GET {{localhost}}/projects/1

### Create new project

POST {{localhost}}/projects
Content-Type: application/json

{
    "name": "Dummy project"
}
### Create many new projects
POST {{localhost}}/projects/many
Content-Type: application/json

[
    {       
        "name": "E-commerce Platform"
    },
    {     
        "name": "Mobile Banking App"
    },
    {       
        "name": "Healthcare Management System"
    },
    {      
        "name": "Inventory Management"
    },
    {      
        "name": "Social Media Analytics"
    }
]

### Update project
PATCH {{localhost}}/projects/1
Content-Type: application/json

{
    "name": "projectService"
}

### Delete project
DELETE {{localhost}}/projects/1

### find a project
GET {{localhost}}/projects/122


### Employee Endpoints ###

### GET /employees
GET {{localhost}}/employees

### GET /employees/:id
GET {{localhost}}/employees/1

### GET /employees/search?name=IT
GET {{localhost}}/employees?name=john

### POST /employees
POST {{localhost}}/employees
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@Gmail.com",
    "departmentId": 2
}

### PATCH /employees/:id
PATCH {{localhost}}/employees/3
Content-Type: application/json

{   "name": "John Doe",
    "email": "john@Gmail.com",
    "departmentId": 12,
    "projectId": 13
}

### DELETE /employees/:id
DELETE {{localhost}}/employees/1
