export const MICROSERVICES_CLIENT = {
    USERS_SERVICES: 'USERS_SERVICES',
    ORDERS_SERVICES: 'ORDERS_SERVICES',
    PRODUCTS_SERVICES: 'PRODUCTS_SERVICES',
    PAYMENTS_SERVICES: 'PAYMENTS_SERVICES',
    NOTIFICATIONS_SERVICES: 'NOTIFICATIONS_SERVICES',
}