@localhost = http://localhost:8000

### Users Endpoints ###

### Create user
POST {{localhost}}/users
Content-Type: application/json

{
    "username": "johndoe2",
    "email": "john@example.com",
    "password": "strongPassword123",
    "role": "user",
    "avatar": "https://example.com/avatars/johndoe.jpg",
    "bio": "Full stack developer passionate about NestJS"
}

### Get all users
GET {{localhost}}/users

### Get user by UUID
GET {{localhost}}/users/67b8ab0d460d4b50f695ca12

### Update user
PATCH {{localhost}}/users/67b8ab0d460d4b50f695ca12
Content-Type: application/json

{
    "username": "johndoe_updated",
    "email": "john.updated@example.com",
    "role": "admin",
    "avatar": "https://example.com/avatars/johndoe_new.jpg",
    "bio": "Senior full stack developer"
}

### Delete user
DELETE {{localhost}}/users/67b8ab0d460d4b50f695ca12