services:
  mysql:
    image: mysql:8.0
    container_name: book-vault-db-container
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  redis:
    image: redis:alpine3.21
    container_name: book-vault-redis-cache-container
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mysql_data:
  redis_data:
